version: '3.3'
services:
    web:
      build: .
      ports:
          - '5000:5000'
      volumes:
          - '.:/code'
      restart: always
      environment:
        FLASK_ENV: development
        FLASK_APP: forecast_app