# Run pytest in github actions
name: run_pytest
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.lock
      - name: Install tensorflow separately
        run: pip install tensorflow==2.7.0
      - name: Run pytest
        run: pytest --cov --cov-report=xml
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1
